Welcome the GSoC 2017 students
rails/weblog pull request #114
Opened 2017-05-08 10:11 UTC by gsamokovarov

A blog post to officially welcome the 2017 students.

2017-05-08 12:26 UTC, alexcameron89 requested changes
I only found one change, otherwise it looks good.

2017-05-08 12:26 UTC, alexcameron89 commented on _posts/2017-05-08-gsoc-2017-students.markdown
> +We'd like to shout-out to everyone who participated in this year selection
year -> year's

2017-05-08 12:46 UTC, robin850 commented on _posts/2017-05-08-gsoc-2017-students.markdown
> +We super are excited to announce our accepted Google Summer of Code students
I guess it's the other way around: "We are super excited to ...". Nice post so far ! 👍

2017-05-08 14:33 UTC, gsamokovarov commented on _posts/2017-05-08-gsoc-2017-students.markdown
> +We'd like to shout-out to everyone who participated in this year selection
Thanks!

2017-05-08 14:33 UTC, gsamokovarov commented on _posts/2017-05-08-gsoc-2017-students.markdown
> +We super are excited to announce our accepted Google Summer of Code students
Yes it is, thanks for catching!

2017-05-12 02:15 UTC, rafaelfranca approved these changes

2017-05-12 02:16 UTC, rafaelfranca commented on _posts/2017-05-08-gsoc-2017-students.markdown
> +date: 2017-05-08 18:00:00 -02:00
Can you update the date so I can merge and publish?

2017-05-12 07:20 UTC, gsamokovarov commented on _posts/2017-05-08-gsoc-2017-students.markdown
> +date: 2017-05-08 18:00:00 -02:00
Sure, updated it. 😊

2017-05-12 12:53 UTC, merged